<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var /Users/topanok/projects/magento2/app/design/frontend/Cart/Ajax/Magento_Checkout/templates/cart/item/renderer/actions/remove.phtml
 */
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
$data = $block->getDeletePostJson();
?>
<a href="#"
   title="<?= $block->escapeHtml(__('Remove item')) ?>"
   id="delete-item-from"
   class="action action-delete"
   data-post='<?= /* @noEscape */ $block->getDeletePostJson() ?>'>
    <span>
        <?= $block->escapeHtml(__('Remove item')) ?>
    </span>
</a>
