<?php
/** @var TopanokVendor\Topanok\Block\EntityRepository $block */
$product = $block->getProductById('1');
if (!is_null($product)): ?>
    <h1><?=$product->getName(); ?></h1>
    <p><?=$product->getDescription(); ?></p>
<?php endif; ?>
<?php $productsCheap=$block->getCheapProducts('10'); ?>
<?php if (!is_null($product)):
foreach ($productsCheap as $product): ?>
    <h2><?=$product->getName(); ?></h2>
    <h3><?=$product->getPrice(); ?></h3><br>
<?php endforeach; endif; ?>