<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
$data = (array) json_decode($block->getDeletePostJson());
$id = $data['data']->id;
?>
<a title="<?= $block->escapeHtml(__('Remove item')) ?>"
   onclick="removeItem('<?=$id; ?>')"
   class="action action-delete">
    <span>
        <?= $block->escapeHtml(__('Remove item')) ?>
    </span>
</a>
